# Generated by Django 5.2.7 on 2025-11-10 18:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('duracion_estimada', models.DurationField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, editable=False, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, editable=False, null=True)),
                ('anticipo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_total_estimado', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Costo total ESTIMADO (Mano de Obra Estimada + Indirectos Asignados)', max_digits=12, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, help_text='IVA calculado automáticamente según ParametrosGlobales', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('PRE', 'Presupuesto'), ('ESP', 'Esperando Anticipo'), ('PRO', 'En Proceso'), ('FAC', 'Facturado'), ('COM', 'Completado'), ('CAN', 'Cancelado')], default='PRE', max_length=3)),
                ('anticipo_pagado', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='HorasEstimadasEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, help_text='Total de horas estimadas para este empleado en el proyecto', max_digits=7)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_asignados', to='empleados.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_estimadas', to='costos.proyecto')),
            ],
            options={
                'verbose_name_plural': 'Horas Estimadas por Empleado',
                'unique_together': {('proyecto', 'empleado')},
            },
        ),
    ]
