# Generated by Django 5.2.8 on 2025-11-12 01:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='anticipo_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje del anticipo aplicado sobre el total con IVA', max_digits=5),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='completo_pagado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ganancia_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ganancia aplicado al costo total.', max_digits=5),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='precio_total_con_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio final (precio de venta + IVA)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor monetario del anticipo calculado automáticamente', max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='costo_total_estimado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo total estimado (mano de obra + indirectos)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='duracion_estimada',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de venta sin IVA (calculado automáticamente)', max_digits=12),
        ),
    ]
