# Generated by Django 5.2.7 on 2025-11-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=150)),
                ('salario_diario', models.DecimalField(decimal_places=2, help_text='Salario base por día trabajado', max_digits=10)),
                ('dias_laborados_semana', models.IntegerField(blank=True, help_text='Días que labora a la semana (ej: 5)', null=True)),
                ('horas_laboradas_diarias', models.IntegerField(blank=True, help_text='Horas estándar por día (ej: 8)', null=True)),
                ('dias_vacaciones_anual', models.IntegerField(blank=True, help_text='Días de vacaciones pagadas al año', null=True)),
                ('recargo_vacaciones', models.DecimalField(blank=True, decimal_places=2, help_text='Recargo sobre vacaciones (ej: 0.30)', max_digits=5, null=True)),
                ('dias_aguinaldo_anual', models.IntegerField(blank=True, help_text='Días de aguinaldo', null=True)),
                ('eficiencia', models.DecimalField(blank=True, decimal_places=2, help_text='Factor de eficiencia (ej: 0.85)', max_digits=5, null=True)),
                ('costo_real_hora_ajustado', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='Costo final por hora (calculado)', max_digits=10, null=True)),
                ('salario_bruto_mensual_calculado', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Salario Bruto Mensual (calculado)', max_digits=10, null=True)),
                ('aporte_patronal_isss_mensual', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Aporte patronal mensual ISSS (calculado)', max_digits=10, null=True)),
                ('aporte_patronal_afp_mensual', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Aporte patronal mensual AFP (calculado)', max_digits=10, null=True)),
                ('deduccion_isss_mensual', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Deducción mensual ISSS empleado (calculado)', max_digits=10, null=True)),
                ('deduccion_afp_mensual', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Deducción mensual AFP empleado (calculado)', max_digits=10, null=True)),
                ('total_deducciones_mensual', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Total deducciones mensuales (calculado)', max_digits=10, null=True)),
                ('pago_liquido_mensual', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Pago líquido mensual estimado (calculado)', max_digits=10, null=True)),
            ],
        ),
    ]
