# Generated by Django 5.2.7 on 2025-11-04 13:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_cuenta', models.CharField(choices=[('ACT', 'Activo'), ('PAS', 'Pasivo'), ('PAT', 'Patrimonio'), ('ING', 'Ingreso'), ('GAS', 'Gasto'), ('COS', 'Costo')], max_length=3)),
                ('es_imputable', models.BooleanField(default=True, help_text='Indica si esta cuenta puede recibir asientos (True) o si es una cuenta de grupo (False).')),
            ],
        ),
        migrations.CreateModel(
            name='EstimacionCostoIndirectoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Alquiler, Luz, Sueldos administrativos, etc.', max_length=200, unique=True)),
                ('monto_estimado_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estimación de Costo Indirecto Global',
                'verbose_name_plural': 'Estimaciones de Costos Indirectos Globales',
            },
        ),
        migrations.CreateModel(
            name='ParametrosGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronal_seguro_social', models.DecimalField(decimal_places=4, default=Decimal('0.0750'), max_digits=5)),
                ('patronal_afp', models.DecimalField(decimal_places=4, default=Decimal('0.0875'), max_digits=5)),
                ('empleado_seguro_social', models.DecimalField(decimal_places=4, default=Decimal('0.0300'), max_digits=5)),
                ('empleado_afp', models.DecimalField(decimal_places=4, default=Decimal('0.0725'), max_digits=5)),
                ('dias_laborados_semana', models.IntegerField(default=5)),
                ('horas_laboradas_diarias', models.IntegerField(default=8)),
                ('recargo_vacaciones', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=5)),
                ('eficiencia_base', models.DecimalField(decimal_places=2, default=Decimal('0.85'), max_digits=5)),
                ('horas_directas_estimadas_mensual', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Horas directas estimadas por mes', max_digits=10)),
                ('tasa_gastos_indirectos_por_hora', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('porcentaje_iva', models.DecimalField(decimal_places=4, default=Decimal('0.13'), help_text='Tasa de IVA como decimal (ej: 0.13 para 13%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.TextField()),
                ('tipo', models.CharField(choices=[('DIARIO', 'Asiento Diario'), ('CIERRE', 'Asiento de Cierre')], default='DIARIO', max_length=10)),
                ('proyecto_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_contables', to='costos.proyecto')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='libromayor.periodocontable')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='libromayor.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='libromayor.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial_debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_inicial_haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_debe_mes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_haber_mes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_final_deudor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_final_acreedor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libromayor.cuenta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libromayor.periodocontable')),
            ],
            options={
                'unique_together': {('cuenta', 'periodo')},
            },
        ),
    ]
